name: navigator_cubit
description: Simple, stateful navigation using Cubit
version: 1.0.0
repository: https://github.com/netsells/navigator_cubit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  import_sorter: ^4.5.1
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.3

import_sorter:
  emojis: true
